### ISSUE TITLE
Search bar glitch after returning from course

### ISSUE THREAD

**Issue by bjrne** [openHPI/xikolo-ios#515] opened 2018-03-20 02:32 UTC
**Affected Component:**
CourseListViewController

**Expected Behavior:**
It should be usable again

**Actual Behavior:**
After going back from a course from search results, the search bar is overlapping the navigation bar and more.. Furthermore you can't cancel the search anymore, so the app is unusable until you restart it.

**Additional Notes:**
Seen on an iPhone 6 simulator after scrolling to the end of the search results

![simulator screen shot - iphone 6 - 2018-03-19 at 14 37 10](https://user-images.githubusercontent.com/7229585/37632582-e8cb108c-2bbc-11e8-8c8e-06e9f2a4ead4.png)

**Comment by Cemoo** [comment] 2018-06-06 11:12
Hi

i tried to get that issue but icouldnt catch it. Also i tried iphone 6 simulator. Is there any record that taken when you were doing that case?

**Comment by mathebox** [comment] 2018-08-09 09:36
I'm also not able to reproduce this. I'm closing this for now. Feel free to reopen the issue if you found a way to reproduce. Thanks @Cemoo for looking into this.

**Closed by mathebox** 2018-08-09 09:36 UTC
Labels: P2: required, bug
