### ISSUE TITLE
VSDG

### ISSUE THREAD

**Issue by HuuPhuocNguyen** [openHPI/xikolo-ios#741] opened 2020-02-25 16:01 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Affected Component**
View, ViewController, ...

**Additional context**

**Comment by HuuPhuocNguyen** [comment] 2020-02-25 16:01
Thank you

**Comment by mathebox** [comment] 2020-02-25 18:35
Duplicate of #740

**Closed by mathebox** 2020-02-25 18:35 UTC
